import enum


class CharacterGender(enum.Enum):
    MALE = "Male"
    FEMALE = "Female"


class CharacterCauseOfDeath(enum.Enum):
    MURDERED_BY_CAIN = "Murdered by Cain"
    TAKEN_TO_HEAVEN = "Taken to Heaven"
    TRANSFORMED_INTO_PILAR_OF_SALT = "Transformed into Pilar of Salt"


class CharacterNationality(enum.Enum):
    EDEN = "Eden"
    ENOCH = "Enoch"
    GOMER = "Gomer"
    MAGOG = "Magog"
    MADAI = "Madai"
    JAVAN = "Javan"
    TUBAL = "Tubal"
    MESHECH = "Meshech"
    TIRAS = "Tiras"
    ASHKENAZ = "Ashkenaz"
    RIPHATH = "Riphath"
    TOGARMAH = "Togarmah"
    ELISHAH = "Elishah"
    TARSHISH = "Tarshish"
    KITTIM = "Kittim"
    RHODANIM = "Rhodanim"
    CUSH = "Cush"
    EGYPT = "Egypt"
    PUT = "Put"
    CANAAN = "Canaan"
    SEBA = "Seba"
    HAVILAH_HAM = "Havliah (Ham)"
    SABTAH = "Sabtah"
    RAAMAH = "Raamah"
    SABTECA = "Sabteca"
    SHEBA_HAM = "Sheba (Ham)"
    DEDAN = "Dedan"
    NIMROD = "Nimrod"
    LUDIM = "Ludim"
    ANAMIM = "Anamim"
    LEHABIM = "Lehabim"
    NAPHTUHIM = "Naphtuhim"
    PATHRUSIM = "Pathrusim"
    CASLUHIM = "Casluhim"
    CAPHTORIM = "Caphtorim"
    SIDON = "Sidon"
    HETH = "Heth"
    ELAM = "Elam"
    ASSHUR = "Asshur"
    ARPACHSHAD = "Arpachshad"
    LUD = "Lud"
    ARAM = "Aram"
    UZ = "Uz"
    HUL = "Hul"
    GETHER = "Gether"
    MASH = "Mash"
    SHELAH = "Shelah"
    EBER = "Eber"
    PELEG = "Peleg"
    JOKTAN = "Joktan"
    ALMODAD = "Almodad"
    SHELEPH = "Sheleph"
    HAZARMAVETH = "Hazarmaveth"
    JERAH = "Jerah"
    HADORAM = "Hadoram"
    UZAL = "Uzal"
    DIKLAH = "Diklah"
    OBAL = "Obal"
    ABIMAEL = "Abimael"
    SHEBA_SHEM = "Sheba (Shem)"
    OPHIR = "Ophir"
    HAVILAH_SHEM = "Havilah (Shem)"
    JOBAB = "Jobab"
    UR = "Ur"
    SHINAR = "Shinar"
    ELLASAR = "Ellasar"
    GOIIM = "Goiim"
    SODOM = "Sodom"
    GOMORRAH = "Gomorrah"
    ADMAH = "Admah"
    ZEBOIIM = "Zeboiim"
    BELA = "Bela"
    AMORITE = "Amorite"
    SALEM = "Salem"
    DAMASCUS = "Damascus"
    HEAVEN = "Heaven"


class CharacterPlaceOfDeath(enum.Enum):
    HARAN = "Haran"
    ZOAR = "Zoar"


class CharacterPrimaryOccupation(enum.Enum):
    HUNTER = "Hunter"
    KING = "King"
    PRIEST_KING = "Priest King"
    ABRAM_SERVANT = "Abram's Servant"
    SARAI_SERVANT = "Sarai's Servant"
    ANGEL = "Angel"
